In [1]:
# Importing numpy library
import numpy as np

# QUESTION 1 (a)
# (i) the determinant |A|.

In [2]:
A = np.array([
    [-2, 0, 0, 0],
    [0, -2, 0, 0],
    [24, -12, 2, 0],
    [0, 0, 0, 2]])

# The Determinant of a lower triangular matrix 4x4 is the product of its diagonal elements.
# Computing the determinant as the product of the diagonal elements.
Determinant = round(np.linalg.det(A))
print("The Determinant of a given lower triangular matrix is :", Determinant)

The Determinant of a given lower triangular matrix is : 16


# QUESTION 1 (a) (ii)
# Calculating the inverse A−1. of the dataset provided

In [3]:
InvMatrix = np.linalg.inv(A)
print(f'The Inverse of a given lower triangular matrix is : \n {InvMatrix}')

The Inverse of a given lower triangular matrix is : 
 [[-0.5  0.   0.   0. ]
 [-0.  -0.5 -0.  -0. ]
 [ 6.  -3.   0.5  0. ]
 [ 0.   0.   0.   0.5]]


# QUESTION 1 (a)(iii) 
# The diagonalizable matrix D similar to A.
# Calculating the eigenvalues and eigenvectors of Matrix A

In [5]:
EVal, EVec = np.linalg.eig(A)

# Create the diagonal matrix D from the eigenvalues
D = np.diag(EVal)

# Invert the matrix of eigenvectors to obtain P^(-1)
PInv = np.linalg.inv(EVec)

# P is the matrix of eigenvectors
P = EVec  

# Checking to find out if D is similar to A
Same = np.allclose(D, PInv @ A @ P)

print("Given Lower Triangular Matrix A:")
print(A)
print("\nDiagonal Matrix D:")
print(D)
print("\nMatrix P:")
print(P)
print("\nD is similar to A:", Same)

Given Lower Triangular Matrix A:
[[ -2   0   0   0]
 [  0  -2   0   0]
 [ 24 -12   2   0]
 [  0   0   0   2]]

Diagonal Matrix D:
[[ 2.  0.  0.  0.]
 [ 0. -2.  0.  0.]
 [ 0.  0. -2.  0.]
 [ 0.  0.  0.  2.]]

Matrix P:
[[ 0.          0.16439899  0.          0.        ]
 [ 0.          0.          0.31622777  0.        ]
 [ 1.         -0.98639392  0.9486833   0.        ]
 [ 0.          0.          0.          1.        ]]

D is similar to A: True
